# Generated by Django 3.2.13 on 2022-06-29 04:23

from django.db import migrations, models
import social.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', upload_to=social.helpers.get_filename),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(default='default_cover.jpg', upload_to=social.helpers.get_filename),
        ),
    ]
