# Generated by Django 4.0.5 on 2022-06-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
